project_id = "zldcotumxouasgzdsvmh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.export-data]
verify_jwt = false

[functions.generate-social-content]
verify_jwt = true

[functions.publish-social-content]
verify_jwt = true

[functions.airbnb-oauth-token]
verify_jwt = true

[functions.airbnb-sync]
verify_jwt = true

[functions.airbnb-reservations]
verify_jwt = true